### ISSUE TITLE
Script to create PSDs

### ISSUE THREAD

**Issue by avivajpeyi** [gwastro/3-ogc#2]
Hi again! 

I see that you have a description in text on how to create the PSDs used for analysis: 
> We use 512 seconds of data around each candidate (with the exception of GW190725 174728) to
estimate the local power spectral density (PSD) using
a version of Welch’s method (Brown 2004). The data is
divided into overlapping segments (8s duration for BBH;
16s for BNS) which are Hann-windowed. The final PSD
estimate is the result of taking the mean of the median
average of the odd and even segments’ power spectrum.

Im happy to follow this and re-create the PSDs. However, I was wondering -- would it be possible to upload a script to create a PSD from the `ini` for an event? 

Is it something like the following: 
```python
from pycbc.psd import welch, interpolate
ts = Merger("EVENT_NAME").strain(ifo)
psd = interpolate(welch(ts), 1.0 / ts.duration)
```

Alternatively, would it be possible to share the PSD files that were used for GW151226's analysis? 

Thanks! :)

**Comment by yi-fan-wang** [comment]
Hi! @avivajpeyi If you want to only estimate PSD, you can refer to the pycbc documentation [here] (http://pycbc.org/pycbc/latest/html/workflow/pycbc_make_psd_estimation_workflow.html).

We have also released all events' psd in the `psds` folder.
